from globals import *
from globales import *

def render_menu(font, tetris_font):
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_tetriste)
    Py.draw.rect(screen, Py.Color(255, 255, 255), barre_rect_normal)
    Py.draw.rect(screen, Py.Color(255, 255, 255), barre_rect_time_attack)
    Py.draw.rect(screen, Py.Color(255, 255, 255), barre_rect_survival)
    Py.draw.rect(screen, Py.Color(255, 255, 255), barre_rect_hall_of_fame)
    screen.blit(image_bcg_menu, (0,0))
    text_titre = tetris_font.render('Tetriste', True, ('blue'))
    titre_text = text_titre.get_rect(center=rect_tetriste.center)
    screen.blit(text_titre, titre_text)
    text_normal = font.render('Normal', True, ('blue'))
    normal_text = text_normal.get_rect(center=barre_rect_normal.center)
    screen.blit(text_normal, normal_text)
    text_time_attack = font.render('Time attack', True, ('blue'))
    time_attack_text = text_time_attack.get_rect(center=barre_rect_time_attack.center)
    screen.blit(text_time_attack, time_attack_text)
    text_survival = font.render('Survival', True, ('blue'))
    survival_text = text_survival.get_rect(center=barre_rect_survival.center)
    screen.blit(text_survival, survival_text)
    text_hall_of_fame = font.render('Hall of Fame', True, ('blue'))
    hall_of_fame_text = text_hall_of_fame.get_rect(center=barre_rect_hall_of_fame.center)
    screen.blit(text_hall_of_fame, hall_of_fame_text)