from globals import *
from globales import *

def render_hall_of_fame(tetris_font, font):
    screen.blit(image_bcg_hall_of_fame, (0,0))
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_hall_of_fame)
    text_titre = tetris_font.render('Hall Of Fame', True, ('blue'))
    titre_text = text_titre.get_rect(center=rect_hall_of_fame.center)
    screen.blit(text_titre, titre_text)
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_mode_normal)
    text_normal = font.render('Mode Normal', True, ('blue'))
    normal_text = text_normal.get_rect(center=rect_mode_normal.center)
    screen.blit(text_normal, normal_text)
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_mode_survival)
    text_survival = font.render('Mode Survival', True, ('blue'))
    survival_normal = text_survival.get_rect(center=rect_mode_survival.center)
    screen.blit(text_survival, survival_normal)

def render_hall_of_fame_normal(tetris_font, font):
    screen.blit(image_bcg_hall_of_fame, (0,0))
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_hall_of_fame)
    text_titre = tetris_font.render('Hall Of Fame', True, ('blue'))
    titre_text = text_titre.get_rect(center=rect_hall_of_fame.center)
    screen.blit(text_titre, titre_text)
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_mode_normal)
    text_normal = font.render('Mode Normal', True, ('blue'))
    normal_text = text_normal.get_rect(center=rect_mode_normal.center)
    screen.blit(text_normal, normal_text)
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_mode_survival)
    text_survival = font.render('Mode Normal', True, ('blue'))
    survival_normal = text_survival.get_rect(center=rect_mode_survival.center)
    screen.blit(text_survival, survival_normal)

def render_hall_of_fame_survival(tetris_font, font):
    screen.blit(image_bcg_hall_of_fame, (0,0))
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_hall_of_fame)
    text_titre = tetris_font.render('Survival', True, ('blue'))
    titre_text = text_titre.get_rect(center=rect_hall_of_fame.center)
    screen.blit(text_titre, titre_text)
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_premier)
    text_premier = font.render('Premier', True, ('blue'))
    premier_text = text_premier.get_rect(center=rect_premier.center)
    screen.blit(text_premier, premier_text)
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_deuxieme)
    text_deuxieme = font.render('Deuxieme', True, ('blue'))
    deuxieme_normal = text_deuxieme.get_rect(center=rect_deuxieme.center)
    screen.blit(text_deuxieme, deuxieme_normal)
    Py.draw.rect(screen, Py.Color(255, 255, 255), rect_troisieme)
    text_troisieme = font.render('Troisieme', True, ('blue'))
    troisieme_normal = text_troisieme.get_rect(center=rect_troisieme.center)
    screen.blit(text_troisieme, troisieme_normal)